### ISSUE TITLE
Zooming in on another planet has trapped me without flight

### ISSUE THREAD

**Issue by cdeath-zz** [sp00ktober/DSP_Mod#1]
This is a really great idea, I hate the fact that you can't check on your other planets by just zooming in on them.  So I just started a new game with some light modding (no new buildings, just tweaks).  I was checking it out and was looking at the other planets in my system, I looked at the normal planets (not gas giant).  When I returned to the world view I was suddenly stuck on another planet!  I could interact with it normally so was basically teleported.  The strange part is that wasn't even the planet I was looking at right then (it was the first one I had looked at).
I'll try to give some helpful information here.
Mods installed in loaded order:
No_Advisor
MegaSystems
RenderDistance (0.6.0)
More_Replication
CopyInserters
MinerInfo
MineralExhaustionNotifier
SmolSplitters
NoAutoZoomIn
DSP_Drone_Clearing
I am using the r2modman to load these with all default configurations.
I will attempt to replicate the issue to see if I can get back to the starting planet and hopefully not lose my progress by loading my manual save.  If there is anything more I find out I will post here.

**Comment by sp00ktober** [comment]
Thanks for the information!

I was hoping that i had fixed this issue before release. I actually need to teleport the player to the remote planet in order to open the planet view, but it should teleport you back to where you was before.
I will also try to reproduce what you did, could you mayb also give me your seed?

**Comment by cdeath-zz** [comment]
Hmm is that the Cluster number on the pause screen?  25851373-64-A10
Unfortunately I played with it and could not get it to move me to any other planets.  I do notice that it shows the icarus light on the other planets so I guessed that you were moving icarus but invisible.  Side note, sometimes the light stays on the planet after going back to your planet you are on.  My system has 2 moons on the gas giant so I can see the other planet from mine and the light was still there.

I guess you'll see this in the seed, but my system has 1 barren close planet, 1 far ice planet, 2 moons on the gas giant and the second moon is a desert high wind, and that is the one I got stuck on.  It may be nothing, but those 2 moons were very close to each other when I was looking around and MAYBE? that has something to do with it, but I have not been able to duplicate the teleportation.

**Comment by cdeath-zz** [comment]
I was able to duplicate the issue a few times.  I selected a planet, immediately zoomed out and selected another planet then canceled.  It put me on the first planet I selected after canceling on the second planet.  I was able to get to the second moon and back doing this.

**Comment by sp00ktober** [comment]
That sounds really good, will try that when i get home :)

**Comment by sp00ktober** [comment]
21d9daa should fix that issue, thanks again for reporting it!
