### ISSUE TITLE
Request: Remote View Toggle

### ISSUE THREAD

**Issue by Dumpshock** [sp00ktober/DSP_Mod#10]
I'd like to request a config toggle to enable/disable the remote planet view feature.
Other mods attempt to also add this feature and might conflict, or some may not wish to use the feature.

I'd like to also suggest renaming the generated config file to something descriptive to the mod. 
Currently, it generates as 'com.sp00ktober.DSPMods', which doesn't at a glance let you know it is the config for RenderDistance.

**Comment by sp00ktober** [comment]
I will see how i can integrate this with the game's vanilla feature of the wheel that popsup when you click a planet.

As for the config name i will see what i can do.

**Comment by sp00ktober** [comment]
You can now enter remote planet view mode by pressing the magnifier from the wheel.
Also added a config option to enabled/disable the remote planet view feature.

**Comment by sp00ktober** [comment]
implemented by 2becb2f
