### ISSUE TITLE
Needs an option to disable auto-planetview 

### ISSUE THREAD

**Issue by Hyratel** [sp00ktober/DSP_Mod#14]
Also, possibly check for and respect the toggle-state of NoAutoZoomIn by jinxOAO. current RenderDistance autoview functionality supersedes the above mentioned mod, which I refuse to abbreviate

**Comment by sp00ktober** [comment]
I have added an option to disable the remote planet view feature in the latest release, you might want to check if it solves your issue?

**Comment by sp00ktober** [comment]
seems like its solved.
