### ISSUE TITLE
Backend code used to preview planets can drop player in space

### ISSUE THREAD

**Issue by Hyratel** [sp00ktober/DSP_Mod#15]
When selecting other planets, the 'teleport Icarus to viewed planet' used to preview the planet can sometimes (unknown cause) leave the player in deep space

**Comment by sp00ktober** [comment]
Which version do you use?

**Comment by Hyratel** [comment]
0.6.9, the version r2modman gets from Thunderstore

**Comment by sp00ktober** [comment]
Try with 0.7.0

**Comment by sp00ktober** [comment]
seems like its solved
