### ISSUE TITLE
Viewing distant planets teleports Icarus to them

### ISSUE THREAD

**Issue by gabriel-dehan** [sp00ktober/DSP_Mod#2]
Hello, just run a brand new game, got on the starter planet, wanted to check-out the system, and when I go to the Star view and look at other planets, Icarus gets teleported to those. I guess its because you are not supposed to access the Planet view without being on the planet so the game teleports you to it. I have reproduced it 10 out of 10 times (before finding it was your mod the culprit).

**Comment by sp00ktober** [comment]
Do you get teleported back when you exit planet view?
I mean you are right, Icarus needs to get to the remote planet in order to open the planet view. But you should get back to where you were before.

**Comment by gabriel-dehan** [comment]
Just updated to the 0.6.1 and I can't seem to be able to reproduce (I indeed get teleported back). Just noticed the commits from 5 hours ago too, so I guess you had already fixed it, my bad :) I tried it with 0.6 and 0.6.1 and I can reproduce easily in 0.6 but it doesn't happen in 0.6.1 so I can at least confirm the fix :p

**Comment by sp00ktober** [comment]
No problem, and good to hear the fix actually worked for you too :)
