### ISSUE TITLE
Glad to fix one problem but now we have a new one

### ISSUE THREAD

**Issue by cdeath-zz** [sp00ktober/DSP_Mod#3]
So I tried to break it again and no teleporting!  HOWEVER, now there is this really weird issue where you return to the planet and Icarus is HUGE!  It doesn't seem to do it all the time, and sometimes the size goes back to normal.  This time I took a screenshot because it's just hilarious.
![20210224173418_1](https://user-images.githubusercontent.com/4262380/109075403-0fc3ed00-76c7-11eb-811c-def09b7be488.jpg)

**Comment by sp00ktober** [comment]
Yup i know about this, its really weird. I dont know why its happening yet. Afaik if you remote planet view a gas giant it brings you back to normal size.
I will investigate in this when i find the time to do so.. sorry for the inconvenience

**Comment by cdeath-zz** [comment]
Oh it's not a problem, it's funny.
Its just strange that it didn't occur when I was trying to replicate the other issue.
I zoom out of my home planet, then select nearby planet, if I go back now, it doesn't seem to happen.  If I continue to a 3rd planet and 4th planet, then it seems to happen.

What if whenever a player zooms out to the solar system view, you force Icarus to teleport back to the home planet?  (if you aren't already doing that)  Maybe that would help?  It seems to work OK when you are only checking out a single planet.

**Comment by sp00ktober** [comment]
Hmm i had this happening when i only checked out one single planet. Strange thing is i even try to reset icarus size when teleporting back, yet it seems to either make him smaller or bigger than he should be. Without this he would grow even bigger tho, see this.

![hmmm](https://user-images.githubusercontent.com/79335616/109076708-4fa4c780-76fb-11eb-8608-a7281c291e6c.png)

**Comment by alike03** [comment]
My theory is that Icarus gets recalculated depending on the planet size. If you click on the planet you're on the scale doesn't change.

**Comment by sp00ktober** [comment]
[DSP_RenderDistance.zip](https://github.com/sp00ktober/DSP_Mod/files/6106917/DSP_RenderDistance.zip)
could someone try out this version and see if it fixes it for you? seems to work for me.
what i did was move https://github.com/sp00ktober/DSP_Mod/blob/eba02980c2173cacbe86b0a128c40e46444d0d82/RenderDistance/Class1.cs#L51
just below the `if` block where `ArrivePlanet()` is called (thanks GreyHak for the hint :) )

**Comment by Nordblum** [comment]
This fixed version works flawlessly, the issue is no more.

**Comment by sp00ktober** [comment]
56077b4778cbbce284fd36d55a65d5d8a89b2184 seems to have fixed the issue then :)
thanks for testing.
