### ISSUE TITLE
Exception when viewing planets while not on or around a planet

### ISSUE THREAD

**Issue by GreyHak** [sp00ktober/DSP_Mod#5]
I got the following exception when I viewed a planet in the current system while the mecha was off a planet (no planet name shown in the bottom left).  The problem is in the line (origPlanetId = GameMain.data.localPlanet.id;) where localPlanet is null.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DSP_RenderDistance.DSP_RenderDistance.patch_OnPlanetClick (UIStarmap,UIStarmapPlanet) <0x00090>
(wrapper dynamic-method) UIStarmap.DMD<UIStarmap..OnPlanetClick> (UIStarmap,UIStarmapPlanet) <0x000d7>
UIStarmap.OnScreenClick (UnityEngine.EventSystems.BaseEventData) <0x000d2>
UnityEngine.Events.InvokableCall`1<UnityEngine.EventSystems.BaseEventData>.Invoke (UnityEngine.EventSystems.BaseEventData) <0x00048>
UnityEngine.Events.UnityEvent`1.Invoke (T0) <0x000dc>
UnityEngine.EventSystems.EventTrigger.Execute (UnityEngine.EventSystems.EventTriggerType,UnityEngine.EventSystems.BaseEventData) <0x000b6>
UnityEngine.EventSystems.EventTrigger.OnPointerDown (UnityEngine.EventSystems.PointerEventData) <0x00029>
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerDownHandler,UnityEngine.EventSystems.BaseEventData) <0x0004f>
UnityEngine.EventSystems.ExecuteEvents.Execute<UnityEngine.EventSystems.IPointerDownHandler> (UnityEngine.GameObject,UnityEngine.EventSystems.BaseEventData,UnityEngine.EventSystems.ExecuteEvents/EventFunction`1<UnityEngine.EventSystems.IPointerDownHandler>) <0x0034d>
UnityEngine.EventSystems.EventSystem:Update()

**Comment by cdeath-zz** [comment]
Oops I posted this too.  So I closed that one because this one links to the other discussion.

**Comment by sp00ktober** [comment]
I‘ll have a look at this soon, thanks for reporting :)

**Comment by sp00ktober** [comment]
I fixed the crash and another "teleport to remote planet" bug, but the problem now is when you exit out of the planet view mode you loose your sailing rotation and speed.
When i fixed that i will upload the new version.

**Comment by sp00ktober** [comment]
9371d3a should fix this, maybe you could test it too? @cdeath-zz @GreyHak 
and sorry for not putting you in the readme GreyHak, will change that on the next push :/
