### ISSUE TITLE
Building with drones and then viewing another planet ...

### ISSUE THREAD

**Issue by cdeath-zz** [sp00ktober/DSP_Mod#7]
This must be for one of the crashing fixes, because I never saw this happen before.  However, it causes the drones to fly across the planet to get back to the invisible Icarus, then when you go back to your home planet, you have no drones until they fly back.  That seems to be the only problem with it at this time, I tested to see if any materials were lost or any other strange things, but nothing else.  Here are some drones that are VERY confused.  On this save, I've not yet gotten the sail.
edit ---
drone clearing mod disabled to see if that was causing a problem and I get the same results
![20210225165811_1](https://user-images.githubusercontent.com/4262380/109226118-3d269e80-778c-11eb-961a-78ad906ae256.jpg)

**Comment by sp00ktober** [comment]
Not sure how i can help here as i have no control over the drones from the other mod :/

**Comment by cdeath-zz** [comment]
oh i forgot to mention I disabled the drone mod, so it still happens with vanilla drones

**Comment by sp00ktober** [comment]
hmm then thats something different. Guess i'll need to collect drones before teleporting the player then.

**Comment by sp00ktober** [comment]
eba0298 should fix this. The mod will now refuse to go into remote planet view when there are still drones on their way, you should get a warning about it.
