### ISSUE TITLE
Exception when leaving remote Interplanetary Logistics Station

### ISSUE THREAD

**Issue by Mordenkainen** [sp00ktober/DSP_Mod#9]
If you are looking at the UI of a Interplanetary Logistics Station on a remote planet, and return to Icarus view by hitting ESC, the following exception is reported:

System.IndexOutOfRangeException: Array index is out of range.
at UIPowerGizmo._OnUpdate () [0x00000] in \<filename unknown\>:0
at ManualBehavior._OnUpdate () [0x00000] in \<filename unknown\>:0

This does not seem to happen with remote Planetary stations, nor do you get the error if you close the station UI before hitting ESC.

**Comment by sp00ktober** [comment]
I will have a look at this today or in the next days, depends on when i find some time.
Thanks for reporting it :)

**Comment by Mordenkainen** [comment]
Sure thing, easy enough to work around if you are aware. Let me know if you need logs or anything. Always happy to help a fellow modder!

**Comment by sp00ktober** [comment]
@Mordenkainen could you maybe send me your savegame and tell me which station triggers the bug?
i cant reproduce it on my own save :/

**Comment by sp00ktober** [comment]
closed as i cant reproduce this and i got no response :/
